### ISSUE TITLE
ShapeNetv2_data download error

### ISSUE THREAD

**Issue by kinto1** [yinyunie/RfDNet#16]
The following files/folders have not been downloaded
1. ShapeNetv2_data/point.tar.gz
2. ShapeNetv2_data/pointcloud.tar.gz

How can I download the data mentioned above?

**Comment by yinyunie** [comment]
Hi,

Just noticed that these two links are broken. thx, I will fix it asap, could you first generate these data on your own? I think these scripts should generate the same data.

Best,
Yinyu

**Comment by kinto1** [comment]
I wonder when the links will be restored. My computer has limited storage capacity, so I cannot download the ShapeNet data. Therefore, it seems difficult for me to generate the data using the scripts...

**Comment by yinyunie** [comment]
Hi,

I updated this link. Please have a check.

Best,
Yinyu
