### ISSUE TITLE
Preprocess data download error

### ISSUE THREAD

**Issue by iamyouno** [yinyunie/RfDNet#17]
Hello, Thanks for your great work!!

I think that links for the both following datasets,  
 - Preprocess ScanNet and Scan2CAD data
 - Preprocess ShapeNet data
have expired again.

Can you check above datasets' link?

**Comment by yinyunie** [comment]
Hi,

Please check the updated links.

Best,
Yinyu

**Comment by iamyouno** [comment]
It works well!! Thank you :)
