### ISSUE TITLE
Project not building

### ISSUE THREAD

**Issue by gchal** [yinyunie/RfDNet#2]
Hi, 
thank you for making your codebase public. Unfortunately I cannot build the project, as for the environemt.yml gives an error for the pointnet. I tried to intstall it seperately but still it does not work. Are you sure the project is working with pytorch 1.7.1?

**Comment by yinyunie** [comment]
Hi,

Thanks for reporting this. I have fixed this bug. You can check again.

Best,
Yinyu

**Comment by gchal** [comment]
Thank you! I managed too by pointing to the external folder 🙂

But better be edited by you for future users. 

Have a nice day.
