### ISSUE TITLE
ShapeNetv2_data/watertight_scaled preprocessed ScanNet data not provided 

### ISSUE THREAD

**Issue by KangchengLiu** [yinyunie/RfDNet#4]
In your Preprocessed ScanNet data, `ShapeNetv2_data/watertight_scaled` is not provided (only `watertight_scaled_simplified` is provided). Please provide `ShapeNetv2_data/watertight_scaled`, thanks

**Comment by yinyunie** [comment]
Hi,

`ShapeNetv2_data/watertight_scaled` is quite large and we did not use it directly for our training. If you need it you can follow [here](https://github.com/yinyunie/RfDNet#preprocess-shapenet-data) to generate yourself. Hope this helps you.

Best,
Yinyu

**Comment by Smart-Robotics-Scientist** [comment]
Preprocessed ScanNet data is unavailable, pls check! thx
