### ISSUE TITLE
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools"

### ISSUE THREAD

**Issue by YuQiao0303** [yinyunie/RfDNet#6]
Hi,
I've been trying this code on Windows with Python3.7  Pytorch1.7.1. And I'm having this now:

subprocess.CalledProcessError: Command 'cmd /u /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && set' returned non-zero exit status 255.

The above exception was the direct cause of the following exception:
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visu
al-cpp-build-tools/

I've installed the build tools from the given link and configure my environment variables and all possible solutions from the Internet. But the issue stayed.

Any advice?

Many thanks!

**Comment by yinyunie** [comment]
Hi,

The code was entirely developed on Linux system (Ubuntu). We have not tested it on Windows.  A quick solution would be changing to a Linux machine and run.

Best,
Yinyu

**Comment by YuQiao0303** [comment]
Thank you. I've switched to Linux and it worked.
