### ISSUE TITLE
Same data for validation set and testing set

### ISSUE THREAD

**Issue by Co1lin** [yinyunie/RfDNet#9]
By chance, I find the data splitting files for validation and testing are identical. I wonder whether it uses the same data for validation and testing.
[test data](https://github.com/yinyunie/RfDNet/blob/main/datasets/splits/fullscan/scannetv2_test.json)
[validation data](https://github.com/yinyunie/RfDNet/blob/main/datasets/splits/fullscan/scannetv2_val.json)

**Comment by yinyunie** [comment]
Hi,

The test set of ScanNet is not labelled. We follow the split as votenet, similar cases can be found in revealnet, where we use val set to evaluate our methods.
